-- CEAMIS Model 3 Fields Migration

ALTER TABLE public.onboarding_data
ADD COLUMN IF NOT EXISTS tanggungan_keluarga INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS city_tier_enc INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS toleransi_rugi_enc INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS save_habit INTEGER NOT NULL DEFAULT 3,
ADD COLUMN IF NOT EXISTS punya_tabungan BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS jumlah_tabungan_bulan NUMERIC(5, 2) NOT NULL DEFAULT 0;
